[package]
name = "valence_protocol"
description = "Protocol library for Minecraft: Java Edition"
readme = "README.md"
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true

[features]
encryption = ["dep:aes", "dep:cfb8"]
compression = ["dep:flate2"]

[dependencies]
valence_math.workspace = true
# valence_generated.workspace = true
valence_text.workspace = true
valence_nbt = { workspace = true, features = ["binary"] }
valence_protocol_macros.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
# byteorder.workspace = true
uuid.workspace = true
valence_ident.workspace = true
base64.workspace = true
url.workspace = true
serde_json.workspace = true
# tracing.workspace = true
bytes.workspace = true
bitfield-struct.workspace = true
# derive_more = { workspace = true, features = ["try_from", "from", "into", "deref", "deref_mut", "as_ref"] }
num-derive.workspace = true
num-traits.workspace = true
cfb8 = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
aes = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true

[build-dependencies]
valence_build_utils.workspace = true
heck.workspace = true
proc-macro2.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
quote.workspace = true
anyhow.workspace = true